-- MySQL Script generated by MySQL Workbench
-- Fri Dec  1 11:21:49 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema default_schema
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema IMDB
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `IMDB` ;

-- -----------------------------------------------------
-- Schema IMDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `IMDB` DEFAULT CHARACTER SET utf8 ;
USE `IMDB` ;

-- -----------------------------------------------------
-- Table `IMDB`.`title_basics`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `IMDB`.`title_basics` ;

CREATE TABLE IF NOT EXISTS `IMDB`.`title_basics` (
  `tconst` INT NOT NULL AUTO_INCREMENT,
  `primary_title` VARCHAR(255) NULL DEFAULT NULL,
  `start_year` VARCHAR(255) NULL DEFAULT NULL,
  `runtime` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`tconst`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `IMDB`.`ratings`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `IMDB`.`ratings` ;

CREATE TABLE IF NOT EXISTS `IMDB`.`ratings` (
  `tconst` INT NOT NULL AUTO_INCREMENT,
  `average_rating` VARCHAR(255) NULL DEFAULT NULL,
  `number_of_votes` VARCHAR(255) NULL DEFAULT NULL,
  `titla_basics_tconst` INT NOT NULL,
  PRIMARY KEY (`tconst`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `IMDB`.`genres`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `IMDB`.`genres` ;

CREATE TABLE IF NOT EXISTS `IMDB`.`genres` (
  `genre_id` INT NOT NULL AUTO_INCREMENT,
  `genre_name` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`genre_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `IMDB`.`titla_basics_has_genres`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `IMDB`.`titla_basics_has_genres` ;

CREATE TABLE IF NOT EXISTS `IMDB`.`titla_basics_has_genres` (
  `titla_basics_tconst` INT NOT NULL,
  `genres_genre_id` INT NOT NULL,
  PRIMARY KEY (`titla_basics_tconst`, `genres_genre_id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
